language: r
os: linux
cache: packages
warnings_are_errors: false

r_packages:
  - covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

r_check_args: "--as-cran --run-dontrun"

matrix:
  include:
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel

notifications:
  email:
    on_success: change
    on_failure: change
